@echo off
cd /d D:\Orbit
echo Removing lock file...
if exist ".git\index.lock" del /f ".git\index.lock"
echo Adding files...
git add lib/screens/home/dm_screen.dart lib/screens/reels/pulse_screen.dart lib/models/music_moment_model.dart lib/screens/reels/capture_moment_screen.dart lib/screens/reels/music_moments_screen.dart lib/services/audio_player_service.dart
echo Committing...
git commit -m "feat: 5 messaging features + Music Moments echo chain"
echo Pushing...
git push origin main
echo Building APK...
set ANDROID_HOME=D:\android-sdk
call flutter build apk --release
echo Copying APK to D:\...
copy /y "build\app\outputs\flutter-apk\app-release.apk" "D:\ORBIT.apk"
echo Done! APK saved to D:\ORBIT.apk
pause